export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY'



export const ALL_PRODUCTS_REQUEST_BY_ID = 'ALL_PRODUCTS_REQUEST_BY_ID'
export const ALL_PRODUCTS_SUCCESS_BY_ID = 'ALL_PRODUCTS_SUCCESS_BY_ID'
export const ALL_PRODUCTS_FAIL_BY_ID = 'ALL_PRODUCTS_FAIL_BY_ID'
export const UPDATE_QUANTITY_BY_ID = 'UPDATE_QUANTITY_BY_ID'

export const CLEAR_ERRORS ='CLEAR_ERRORS'


